export interface Tool {
  id: string
  name: string
  category: "build" | "write" | "design" | "productivity" | "finance" | "global"
  categoryName: string
  description: string
  pricing: string
  pricingFree: boolean
  domesticAvailable: boolean
  opcUsage: string
  url: string
  alternatives?: string[]
}

export const TOOL_CATEGORIES = [
  { id: "build" as const, name: "建站开发" },
  { id: "write" as const, name: "写作内容" },
  { id: "design" as const, name: "设计图像" },
  { id: "productivity" as const, name: "效率管理" },
  { id: "finance" as const, name: "财税合规" },
  { id: "global" as const, name: "出海工具" },
] as const

export const TOOLS: Tool[] = [
  // ===== build（建站开发）=====
  {
    id: "cursor",
    name: "Cursor",
    category: "build",
    categoryName: "建站开发",
    description: "AI驱动的代码编辑器，基于VS Code，内置AI辅助编程",
    pricing: "免费版可用，Pro $20/月",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "一人公司核心开发工具，AI辅助写全栈代码",
    url: "https://cursor.sh",
  },
  {
    id: "v0",
    name: "V0.dev",
    category: "build",
    categoryName: "建站开发",
    description: "Vercel出品的AI UI生成工具，输入描述生成React组件",
    pricing: "免费额度，Pro $20/月",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "快速生成前端页面原型，节省UI开发时间",
    url: "https://v0.dev",
  },
  {
    id: "bolt",
    name: "Bolt.new",
    category: "build",
    categoryName: "建站开发",
    description: "浏览器内AI全栈开发环境，对话式生成完整应用",
    pricing: "免费试用，Pro $20/月",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "零配置快速搭建MVP原型验证想法",
    url: "https://bolt.new",
  },
  {
    id: "netlify",
    name: "Netlify",
    category: "build",
    categoryName: "建站开发",
    description: "现代Web应用托管平台，支持自动部署和Serverless函数",
    pricing: "免费套餐够用，Pro $19/月",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "一键部署个人官网和SaaS产品前端",
    url: "https://www.netlify.com",
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "build",
    categoryName: "建站开发",
    description: "Next.js官方托管平台，极速部署和全球CDN",
    pricing: "Hobby免费，Pro $20/月",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "部署Next.js项目的首选，自动CI/CD",
    url: "https://vercel.com",
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "build",
    categoryName: "建站开发",
    description: "开源Firebase替代，提供PostgreSQL数据库、认证、存储",
    pricing: "免费套餐含500MB，Pro $25/月",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "一人公司后端基础设施，数据库+认证一站搞定",
    url: "https://supabase.com",
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    category: "build",
    categoryName: "建站开发",
    description: "GitHub出品的AI编程助手，实时代码补全和建议",
    pricing: "个人版 $10/月",
    pricingFree: false,
    domesticAvailable: false,
    opcUsage: "日常编码提速，自动补全重复代码",
    url: "https://github.com/features/copilot",
  },
  {
    id: "replit",
    name: "Replit",
    category: "build",
    categoryName: "建站开发",
    description: "在线IDE和部署平台，支持AI辅助开发和即时部署",
    pricing: "免费版可用，Pro $25/月",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "在线快速开发和分享代码原型",
    url: "https://replit.com",
  },
  {
    id: "railway",
    name: "Railway",
    category: "build",
    categoryName: "建站开发",
    description: "现代云部署平台，一键部署后端服务和数据库",
    pricing: "按量计费，每月$5免费额度",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "部署后端API和数据库服务",
    url: "https://railway.app",
  },
  {
    id: "cloudflare-pages",
    name: "Cloudflare Pages",
    category: "build",
    categoryName: "建站开发",
    description: "Cloudflare静态站点和全栈应用托管，全球边缘网络",
    pricing: "免费套餐非常慷慨",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "国内可访问的免费建站托管方案",
    url: "https://pages.cloudflare.com",
  },

  // ===== write（写作内容）=====
  {
    id: "claude",
    name: "Claude",
    category: "write",
    categoryName: "写作内容",
    description: "Anthropic出品的AI助手，擅长长文写作、分析和编程",
    pricing: "免费版可用，Pro $20/月",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "撰写商业计划书、产品文案和技术文档",
    url: "https://claude.ai",
  },
  {
    id: "kimi",
    name: "Kimi",
    category: "write",
    categoryName: "写作内容",
    description: "月之暗面出品，支持超长上下文，擅长中文内容理解",
    pricing: "免费使用",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "长文档分析、市场调研报告生成",
    url: "https://kimi.moonshot.cn",
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    category: "write",
    categoryName: "写作内容",
    description: "OpenAI旗舰AI对话产品，通用能力强大",
    pricing: "免费版可用，Plus $20/月",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "通用AI助手，头脑风暴和内容创作",
    url: "https://chat.openai.com",
  },
  {
    id: "doubao",
    name: "豆包",
    category: "write",
    categoryName: "写作内容",
    description: "字节跳动AI助手，中文理解能力优秀",
    pricing: "免费使用",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "日常中文内容创作和社交媒体文案",
    url: "https://www.doubao.com",
  },
  {
    id: "wenxin",
    name: "文心一言",
    category: "write",
    categoryName: "写作内容",
    description: "百度大模型产品，深度适配中文场景",
    pricing: "免费使用",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "中文SEO文章和营销内容生成",
    url: "https://yiyan.baidu.com",
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    category: "write",
    categoryName: "写作内容",
    description: "Notion内置AI写作助手，无缝融入笔记工作流",
    pricing: "需Notion付费版 $10/月起",
    pricingFree: false,
    domesticAvailable: false,
    opcUsage: "在知识库中直接AI辅助写作和整理",
    url: "https://www.notion.so/product/ai",
  },
  {
    id: "miaoda",
    name: "秒哒",
    category: "write",
    categoryName: "写作内容",
    description: "百度出品的AI应用开发平台，支持多Agent协作",
    pricing: "免费使用",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "快速搭建AI工作流自动化内容生产",
    url: "https://miaoda.baidu.com",
  },
  {
    id: "gamma",
    name: "Gamma",
    category: "write",
    categoryName: "写作内容",
    description: "AI驱动的演示文稿生成工具，输入大纲自动生成PPT",
    pricing: "免费版可用，Plus $10/月",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "快速制作融资路演和产品介绍PPT",
    url: "https://gamma.app",
  },
  {
    id: "xinghuo",
    name: "讯飞星火",
    category: "write",
    categoryName: "写作内容",
    description: "科大讯飞AI大模型，语音识别和中文能力突出",
    pricing: "免费使用",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "语音转文字、会议纪要和中文写作",
    url: "https://xinghuo.xfyun.cn",
  },
  {
    id: "minimax",
    name: "MiniMax",
    category: "write",
    categoryName: "写作内容",
    description: "国产大模型，支持文本、语音、视觉多模态",
    pricing: "免费使用",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "多模态内容生成和智能客服搭建",
    url: "https://www.minimax.chat",
  },
  {
    id: "perplexity",
    name: "Perplexity",
    category: "write",
    categoryName: "写作内容",
    description: "AI搜索引擎，实时联网搜索并生成带引用的回答",
    pricing: "免费版可用，Pro $20/月",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "竞品调研和市场信息搜集分析",
    url: "https://www.perplexity.ai",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    category: "write",
    categoryName: "写作内容",
    description: "深度求索出品，开源大模型，推理能力强",
    pricing: "免费使用",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "代码辅助和技术文档写作",
    url: "https://chat.deepseek.com",
  },

  // ===== design（设计图像）=====
  {
    id: "midjourney",
    name: "Midjourney",
    category: "design",
    categoryName: "设计图像",
    description: "顶级AI图像生成工具，艺术风格突出",
    pricing: "Basic $10/月起",
    pricingFree: false,
    domesticAvailable: false,
    opcUsage: "生成产品宣传图和品牌视觉素材",
    url: "https://www.midjourney.com",
  },
  {
    id: "stable-diffusion",
    name: "Stable Diffusion",
    category: "design",
    categoryName: "设计图像",
    description: "开源AI图像生成模型，可本地部署",
    pricing: "开源免费，云端按量计费",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "本地部署生成商用图片，无版权顾虑",
    url: "https://stability.ai",
  },
  {
    id: "flux",
    name: "Flux",
    category: "design",
    categoryName: "设计图像",
    description: "Black Forest Labs出品，新一代开源图像生成模型",
    pricing: "开源免费，API按量计费",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "高质量产品图和营销素材生成",
    url: "https://blackforestlabs.ai",
  },
  {
    id: "canva",
    name: "Canva",
    category: "design",
    categoryName: "设计图像",
    description: "在线设计平台，海量模板，支持AI生成",
    pricing: "免费版可用，Pro ¥348/年",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "快速制作社交媒体图片和营销海报",
    url: "https://www.canva.cn",
  },
  {
    id: "jimeng",
    name: "即梦AI",
    category: "design",
    categoryName: "设计图像",
    description: "字节跳动AI创作平台，支持图像和视频生成",
    pricing: "免费使用",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "生成短视频封面和社交媒体配图",
    url: "https://jimeng.jianying.com",
  },
  {
    id: "kling",
    name: "可灵AI",
    category: "design",
    categoryName: "设计图像",
    description: "快手出品的AI视频生成工具，效果惊艳",
    pricing: "免费试用，会员制",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "生成产品演示视频和广告素材",
    url: "https://klingai.kuaishou.com",
  },
  {
    id: "adobe-firefly",
    name: "Adobe Firefly",
    category: "design",
    categoryName: "设计图像",
    description: "Adobe AI图像生成，商用安全，集成Creative Cloud",
    pricing: "免费额度，付费 $4.99/月起",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "生成商用安全的营销图片素材",
    url: "https://firefly.adobe.com",
  },
  {
    id: "figma",
    name: "Figma",
    category: "design",
    categoryName: "设计图像",
    description: "协作式UI设计工具，行业标准",
    pricing: "个人免费，专业版 $15/月",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "产品UI/UX设计和设计系统管理",
    url: "https://www.figma.com",
  },
  {
    id: "logoai",
    name: "LogoAI",
    category: "design",
    categoryName: "设计图像",
    description: "AI Logo生成工具，输入品牌名自动设计Logo",
    pricing: "预览免费，下载 $29起",
    pricingFree: false,
    domesticAvailable: true,
    opcUsage: "快速生成品牌Logo和视觉识别",
    url: "https://www.logoai.com",
  },
  {
    id: "recraft",
    name: "Recraft",
    category: "design",
    categoryName: "设计图像",
    description: "AI矢量图和插画生成工具，支持风格一致性",
    pricing: "免费版可用，Pro $25/月",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "生成品牌风格统一的图标和插画",
    url: "https://www.recraft.ai",
  },

  // ===== productivity（效率管理）=====
  {
    id: "feishu",
    name: "飞书",
    category: "productivity",
    categoryName: "效率管理",
    description: "字节跳动协作平台，集成文档、表格、会议",
    pricing: "基础版免费，商业版按需",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "一人公司全能协作平台，文档+项目管理",
    url: "https://www.feishu.cn",
  },
  {
    id: "notion",
    name: "Notion",
    category: "productivity",
    categoryName: "效率管理",
    description: "All-in-one工作空间，笔记、数据库、项目管理",
    pricing: "个人免费，Plus $10/月",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "搭建个人知识库和业务管理系统",
    url: "https://www.notion.so",
  },
  {
    id: "zapier",
    name: "Zapier",
    category: "productivity",
    categoryName: "效率管理",
    description: "无代码自动化平台，连接5000+应用",
    pricing: "免费5个Zap，Starter $19.99/月",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "自动化重复工作流，如客户通知、数据同步",
    url: "https://zapier.com",
  },
  {
    id: "make",
    name: "Make",
    category: "productivity",
    categoryName: "效率管理",
    description: "可视化自动化平台（原Integromat），比Zapier更灵活",
    pricing: "免费1000次/月，Core $9/月",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "构建复杂业务自动化工作流",
    url: "https://www.make.com",
  },
  {
    id: "fabumao",
    name: "发布猫",
    category: "productivity",
    categoryName: "效率管理",
    description: "多平台内容分发工具，一键发布到多个自媒体",
    pricing: "免费版可用，VIP ¥99/年",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "一键分发文章到微信、知乎、头条等平台",
    url: "https://www.fabucat.com",
  },
  {
    id: "dida",
    name: "滴答清单",
    category: "productivity",
    categoryName: "效率管理",
    description: "跨平台任务管理和日历工具，简洁高效",
    pricing: "免费版可用，高级版 ¥139/年",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "个人任务管理和项目进度追踪",
    url: "https://dida365.com",
  },
  {
    id: "monica",
    name: "Monica",
    category: "productivity",
    categoryName: "效率管理",
    description: "浏览器AI助手插件，集成ChatGPT等多模型",
    pricing: "免费额度，Pro $9.9/月",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "浏览网页时随时调用AI辅助工作",
    url: "https://monica.im",
  },
  {
    id: "raycast",
    name: "Raycast",
    category: "productivity",
    categoryName: "效率管理",
    description: "macOS效率启动器，集成AI和丰富扩展",
    pricing: "免费版可用，Pro $8/月",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "macOS快速启动和AI快捷操作",
    url: "https://www.raycast.com",
  },
  {
    id: "linear",
    name: "Linear",
    category: "productivity",
    categoryName: "效率管理",
    description: "现代项目管理工具，为开发团队设计",
    pricing: "免费版可用，Standard $8/月",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "产品开发任务跟踪和迭代管理",
    url: "https://linear.app",
  },
  {
    id: "n8n",
    name: "n8n",
    category: "productivity",
    categoryName: "效率管理",
    description: "开源工作流自动化工具，可自托管",
    pricing: "社区版免费，Cloud €20/月",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "自建自动化工作流，数据完全自主可控",
    url: "https://n8n.io",
  },

  // ===== finance（财税合规）=====
  {
    id: "tax-guide",
    name: "小规模纳税人申报指南",
    category: "finance",
    categoryName: "财税合规",
    description: "国家税务总局官方申报指南和流程说明",
    pricing: "免费",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "了解一人公司季度纳税申报流程",
    url: "https://www.chinatax.gov.cn",
  },
  {
    id: "weisuan",
    name: "微算税务",
    category: "finance",
    categoryName: "财税合规",
    description: "智能税务计算和筹划工具",
    pricing: "基础功能免费",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "自动计算税额，优化税务筹划方案",
    url: "https://www.weisuan.com",
  },
  {
    id: "shuiyou",
    name: "税友",
    category: "finance",
    categoryName: "财税合规",
    description: "专业财税服务平台，提供报税和财务管理工具",
    pricing: "按需付费",
    pricingFree: false,
    domesticAvailable: true,
    opcUsage: "在线报税和财务报表生成",
    url: "https://www.servyou.com.cn",
  },
  {
    id: "caoliao",
    name: "草料二维码",
    category: "finance",
    categoryName: "财税合规",
    description: "二维码生成和管理平台，支持表单和电子签",
    pricing: "免费版可用，商业版 ¥298/年",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "生成合同签署二维码，简化签约流程",
    url: "https://cli.im",
  },
  {
    id: "fadada",
    name: "法大大",
    category: "finance",
    categoryName: "财税合规",
    description: "电子合同和电子签章平台，具备法律效力",
    pricing: "按份计费，企业版按需",
    pricingFree: false,
    domesticAvailable: true,
    opcUsage: "在线签署客户合同和保密协议",
    url: "https://www.fadada.com",
  },
  {
    id: "qichacha",
    name: "企查查",
    category: "finance",
    categoryName: "财税合规",
    description: "企业工商信息查询平台",
    pricing: "基础查询免费，VIP ¥360/年",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "查询合作方企业信用和工商信息",
    url: "https://www.qcc.com",
  },
  {
    id: "tianyancha",
    name: "天眼查",
    category: "finance",
    categoryName: "财税合规",
    description: "商业信息查询和企业征信平台",
    pricing: "基础查询免费，VIP ¥360/年",
    pricingFree: true,
    domesticAvailable: true,
    opcUsage: "尽调客户和合作伙伴的企业背景",
    url: "https://www.tianyancha.com",
  },
  {
    id: "huisuanzhang",
    name: "慧算账",
    category: "finance",
    categoryName: "财税合规",
    description: "互联网+代理记账平台，专业财税服务",
    pricing: "小规模 ¥200/月起",
    pricingFree: false,
    domesticAvailable: true,
    opcUsage: "一人公司代理记账和纳税申报外包",
    url: "https://www.huisuanzhang.com",
  },

  // ===== global（出海工具）=====
  {
    id: "shopify",
    name: "Shopify",
    category: "global",
    categoryName: "出海工具",
    description: "全球领先的电商建站平台，支持独立站搭建",
    pricing: "Basic $39/月",
    pricingFree: false,
    domesticAvailable: true,
    opcUsage: "搭建面向海外市场的独立电商站",
    url: "https://www.shopify.com",
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "global",
    categoryName: "出海工具",
    description: "全球在线支付处理平台，开发者友好",
    pricing: "按交易 2.9% + $0.30",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "海外SaaS产品收款和订阅计费",
    url: "https://stripe.com",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    category: "global",
    categoryName: "出海工具",
    description: "AI语音合成和克隆平台，支持多语言",
    pricing: "免费额度，Starter $5/月",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "制作多语言产品介绍和配音内容",
    url: "https://elevenlabs.io",
  },
  {
    id: "gumroad",
    name: "Gumroad",
    category: "global",
    categoryName: "出海工具",
    description: "数字产品销售平台，适合创作者",
    pricing: "按交易 10% 抽成",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "销售数字产品如电子书、模板、课程",
    url: "https://gumroad.com",
  },
  {
    id: "lemonsqueezy",
    name: "Lemon Squeezy",
    category: "global",
    categoryName: "出海工具",
    description: "SaaS和数字产品支付平台，自动处理全球税务",
    pricing: "按交易 5% + $0.50",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "海外SaaS订阅收款，自动处理VAT",
    url: "https://www.lemonsqueezy.com",
  },
  {
    id: "paddle",
    name: "Paddle",
    category: "global",
    categoryName: "出海工具",
    description: "SaaS支付和订阅管理平台，MoR模式处理税务",
    pricing: "按交易 5% + $0.50",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "B2B SaaS海外收款和发票管理",
    url: "https://www.paddle.com",
  },
  {
    id: "producthunt",
    name: "Product Hunt",
    category: "global",
    categoryName: "出海工具",
    description: "新产品发布和发现平台，获取早期用户",
    pricing: "免费",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "海外产品发布获取第一批种子用户",
    url: "https://www.producthunt.com",
  },
  {
    id: "indiehackers",
    name: "IndieHackers",
    category: "global",
    categoryName: "出海工具",
    description: "独立开发者社区，分享创业故事和收入数据",
    pricing: "免费",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "学习海外独立开发者变现经验",
    url: "https://www.indiehackers.com",
  },
  {
    id: "pika",
    name: "Pika",
    category: "global",
    categoryName: "出海工具",
    description: "AI视频生成工具，文本/图片转视频",
    pricing: "免费试用，Standard $10/月",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "制作海外社交媒体营销短视频",
    url: "https://pika.art",
  },
  {
    id: "heygen",
    name: "Heygen",
    category: "global",
    categoryName: "出海工具",
    description: "AI数字人视频平台，支持多语言数字人",
    pricing: "免费试用，Creator $29/月",
    pricingFree: true,
    domesticAvailable: false,
    opcUsage: "制作多语言产品介绍和营销数字人视频",
    url: "https://www.heygen.com",
  },
]
